# Generated by Django 2.0.13 on 2019-05-05 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('entered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_end_date', models.DateTimeField()),
            ],
        ),
    ]
